-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/shorturls (
  su_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  su_namespace INTEGER NOT NULL,
  su_title VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX shorturls_ns_title ON /*_*/shorturls (su_namespace, su_title);
